tilejson support
CartoDB/deck.gl pull request #48
Opened 2020-09-18 15:04 UTC by padawannn

Documentation and test would be missing but I would like to have an opinion

2020-09-18 17:39 UTC, VictorVelarde commented on modules/geo-layers/src/mvt-layer/mvt-layer.js
> +    const url = getURLFromTemplate(this.state.data, tile);
Could you please explain a bit on this change? Can't it be avoided?

2020-09-18 17:41 UTC, VictorVelarde commented on modules/geo-layers/src/tile-layer/tile-layer.js
> +        data = tilejson.tiles
it looks like `data = tilejson.tiles` can be left outside of the if

2020-09-18 17:43 UTC, VictorVelarde commented on modules/geo-layers/src/tile-layer/tile-layer.js
> +        tilejson = await load(tilejson, JSONLoader)
this JSONLoader here looks like a really nice idea!

2020-09-21 07:40 UTC, padawannn commented on modules/geo-layers/src/mvt-layer/mvt-layer.js
> +    const url = getURLFromTemplate(this.state.data, tile);
Yes, sure. As kylebarron said in the RFC, I've had a new property called tilejson so the tile URL can be set using data property or tilejson property. As far as I know, properties are read-only so you cannot change the data property by tiles URL that comes from tilejson property. The solution that I've found is to save the data in the state that can be set by data property or tilejson property

2020-09-21 07:42 UTC, padawannn commented on modules/geo-layers/src/tile-layer/tile-layer.js
> +        data = tilejson.tiles
You are right, thank you!

2020-09-21 15:34 UTC, alasarr commented on modules/geo-layers/src/tile-layer/tile-layer.js
> +  tilejson: null,
Why are we adding a new prop? We don't we just do it as in the RFC inside the property data?

2020-09-21 15:54 UTC, VictorVelarde commented on test/modules/geo-layers/tile-layer/tile-layer.spec.js
> +          t.is(layer.state.tileset.minZoom, tilejson.minZoom, 'Min zoom layer is correct');
Maybe we could prepare 1 test just with the mandatory (tiles) and a different one with these interesting 'extra' tile properties (minZoom, maxZoom, bounds).

Indeed, if the optional `bounds` exists in the tilejson, it could be interesting to store the 'extent'. I think @neokore  could give us some feedback about it, regarding to overzooming.

2020-09-21 18:16 UTC, alasarr requested changes

2020-09-21 18:16 UTC, alasarr commented on modules/geo-layers/src/tile-layer/tile-layer.js
> +      JSON.stringify(props.tilejson) !== JSON.stringify(oldProps.tilejson) ||
Ask about it at deck.gl slack

2020-09-21 18:16 UTC, alasarr commented on modules/geo-layers/src/tile-layer/tile-layer.js
> +      JSON.stringify(props.tilejson) !== JSON.stringify(oldProps.tilejson) ||
The layer shouldn't check this. It should be something the developer needs to manage as done in the examples: https://github.com/visgl/deck.gl/blob/master/examples/get-started/react/basic/app.js#L28

2020-09-21 18:19 UTC, alasarr commented on modules/geo-layers/src/tile-layer/tile-layer.js
> +      minZoom = tilejson.minzoom ? tilejson.minzoom : minZoom;
```js
minZoom =  tilejson.minzoom || minZoom
```

2020-09-21 18:20 UTC, alasarr requested changes
Some changes suggested

2020-09-22 09:12 UTC, padawannn commented on modules/geo-layers/src/tile-layer/tile-layer.js
> +      tilejson: {},
Done

2020-09-22 09:12 UTC, padawannn commented on modules/geo-layers/src/tile-layer/tile-layer.js
> +      tileset.selectedTiles &&
Done (parenthesis comes from linter)

2020-09-22 09:12 UTC, padawannn commented on modules/geo-layers/src/tile-layer/tile-layer.js
> +      JSON.stringify(props.tilejson) !== JSON.stringify(oldProps.tilejson) ||
Done

2020-09-22 09:13 UTC, padawannn commented on modules/geo-layers/src/tile-layer/tile-layer.js
> +      minZoom = tilejson.minzoom ? tilejson.minzoom : minZoom;
Done

2020-09-22 18:21 UTC, closed without merging

2020-09-23 06:05 UTC, neokore commented on test/modules/geo-layers/tile-layer/tile-layer.spec.js
> +          t.is(layer.state.tileset.minZoom, tilejson.minZoom, 'Min zoom layer is correct');
Setting the `extent` value from TileJSON data is done by enabling `autoExtent` in any CARTOlayer, but not at the TileLayer level.

2020-09-23 06:08 UTC, neokore commented on modules/geo-layers/src/tile-layer/tile-layer.js
> +      minZoom = tilejson.minzoom ? tilejson.minzoom : minZoom;
Are we overwriting the custom `minZoom` and `maxZoom` set by the user?